### ISSUE TITLE
Unable to run locally

### ISSUE THREAD

**Issue by nmilosev** [ceylon/ceylon-web-ide-backend#101]
Environment:
===

Fedora 25 (Toshiba Chromebook CB-30)
Mozilla Firefox (latest)

Steps to reproduce:
===
```
# add ceylon repo's and install it
sudo dnf install ceylon-1.3.2
cd ~
git clone https://github.com/ceylon/ceylon-web-ide-backend
cd ceylon-web-ide-backend
git checkout version-1.3.2

ceylon run # ./ceylonb run also not working
```

Error message:
===
```
GET 
http://localhost:8080/modules/ceylon/language/1.3.2/ceylon.language-1.3.2.js [HTTP/1.1 500 Internal Server Error 44ms]

Error: Script error for: ceylon/language/1.3.2/ceylon.language-1.3.2
http://requirejs.org/docs/errors.html#scripterror  require.js:8:252
```

Steps to fix:
===

In root directory of the repo.

```
mkdir -p ./web-content/ceylon/language/1.3.2
cd ./web-content/ceylon/language/1.3.2
wget https://modules.ceylon-lang.org/repo/1/ceylon/language/1.3.2/ceylon.language-1.3.2.js
wget https://modules.ceylon-lang.org/repo/1/ceylon/language/1.3.2/ceylon.language-1.3.2-model.js
```

Finally modify `/home/nmilosev/ceylon-web-ide-backend/web-content/scripts/runner.js`:

```
---    baseUrl: "modules",
+++    baseUrl: "",
```

**Comment by quintesse** [comment]
Actually it's the README that's wrong. The explanation works for release versions. So if you check out a `version-X.Y.Z` branch and run the `ceylonb` (or plain `ceylon` if you have the appropriate compiler installed) command it will work without any changes.

If you want to run the `master` branch you also need the Ceylon distribution from `master`, which you can either build yourself or download a nightly: https://ci-ceylon.rhcloud.com/job/ceylon-distribution/lastSuccessfulBuild/artifact/ceylon/dist/

I updated the README to explain this. Closing.
