### ISSUE TITLE
When hitting Enter, the new line starts with a huge indentation after declaring a sequence

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon-web-ide-backend#72]
Was trying to play a little with Ceylon online, but the editor seems really broken.

When hitting Enter to start a new line, the new line is created with a large indentation and the cursor is placed at the end.

Example, type this then hit Enter:

```ceylon
value map = {1->2};
```

The new line will start with an indentation of 2 or 3 levels!

Tried with Chrome and Safari.

**Comment by quintesse** [comment]
I tried taking a quick look at how the CodeMirror Ceylon support is implemented (https://github.com/ceylon/ceylon-web-ide-backend/blob/master/src/main/webapp/scripts/mode/ceylon/ceylon.js) but it looks pretty complex.

**Comment by quintesse** [comment]
Ok, I've updated the editor on the trybeta site, I think it's fixed now.

**Comment by renatoathaydes** [comment]
Can I access the beta version online?

**Comment by quintesse** [comment]
http://trybeta.ceylon-lang.org

**Comment by renatoathaydes** [comment]
Thanks... any idea why auto-complete does not work for me?
My OS (Linux Mint) does not have a Ctrl+space shortcut, neither does FireFox as far as I know... but when I do Ctrl+Space, no auto-complete shows up... just the play button changes briefly to the moving gearbox icon... after lots of tries and pressing Ctrl+D to see docs, it seems to work, but only intermittently.

**Comment by quintesse** [comment]
Well this was because I accidentally reverted back to the older, much more restricted, version that only does completion on members after you've typed a period (`.`). I fixed it so it's more useful again, thx for the catch.

**Comment by renatoathaydes** [comment]
Cool. There seems to be no keyboard shortcut to run the code? That's very inconvenient and easy to fix! Can you add something like Ctrl+Enter to run?
