### ISSUE TITLE
Share button does not do anything

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon-web-ide-backend#73]
When I hit the "Share" button, I get this error:

```
POST http://try.ceylon-lang.org/share 404 (Not Found)send
 @ require-jquery.js:10155jQuery.extend.ajax
 @ require-jquery.js:9633shareSource
 @ repl.js:182onclick
 @ (index):101
```

Tried with Chrome and Safari.

**Comment by quintesse** [comment]
This is currently being rewritten completely to integrate with GitHub Gist.

**Comment by gavinking** [comment]
This was fixed by @quintesse.

**Comment by quintesse** [comment]
Yes, although the official site will have this error until we release 1.2 (just so you don't go looking there and wonder why nothing seems to have changed @renatoathaydes )
