### ISSUE TITLE
Exceptions don’t work

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-web-ide-backend#75]
- http://trybeta.ceylon-lang.org/?gist=5d7003ca31f00b7add6e
- http://trybeta.ceylon-lang.org/?gist=e29f3951b20408ca8895
- http://trybeta.ceylon-lang.org/?gist=823e84ba7ed07abc4397

all give the same error:
> Runtime error:
--- TypeError: access to strict mode caller function is censored

**Comment by quintesse** [comment]
Are you using FireFox by any chance?

**Comment by quintesse** [comment]
Can you try this fix @lucaswerkmeister ?

**Comment by lucaswerkmeister** [comment]
Yes Firefox, but I’m still getting the error even in a completely fresh profile.

**Comment by lucaswerkmeister** [comment]
https://stackoverflow.com/a/16871135

It seems `Throwable` [uses `.caller` to build the stack trace on JS](https://github.com/ceylon/ceylon.language/blob/32cb209ac27dfe559df992bb9757d5a3e8f7b798/runtime-js/Throwable_cons_before.js#L4). However, `caller` was never specified, and in ES5 it’s explicitly an error to use it in strict mode. So apparently we just can’t use Ceylon exceptions in strict mode, period. Looks like this is something for @chochos.

As for this issue… looks like some function (that calls into Ceylon, and would appear in the stack trace) is still strict?

**Comment by quintesse** [comment]
But I disabled "use strict" in that page, and I don't think Ceylon uses that directive anywhere, does it?

**Comment by lucaswerkmeister** [comment]
There’s still four `"use strict";` that aren’t commented out:
```shell
$ grep -r '"use strict"'
src/main/webapp/scripts/active-line.js:  "use strict";
src/main/webapp/scripts/codemirror.js:  "use strict";
src/main/webapp/scripts/github.js:"use strict";
src/main/webapp/scripts/repl.js:"use strict";
src/main/webapp/scripts/runner.js://"use strict";
```

**Comment by quintesse** [comment]
Like I said: "in that page"

**Comment by lucaswerkmeister** [comment]
`repl.js` is still strict, and that’s what calls `run`.

**Comment by quintesse** [comment]
Yes, that seems to be what's happening, but that's not what the docs for `use strict` say. It specifically mentions that it applies to the block it is found in or to the entire file, it says nothing about inheriting it from parent contexts. Anyway, removing that seems to fix it indeed.

**Comment by lucaswerkmeister** [comment]
Well the entire file `repl.js` is strict, so of course the function that calls into the ceylon code is strict as well – and `Throwable` attempts to walk over this function when collecting the stack trace, error.

**Comment by quintesse** [comment]
Maybe that exception could be captured and the stack walking halted there. Or is that why you mentioned @chochos above? :)

**Comment by lucaswerkmeister** [comment]
I think we should use `Error().stack` instead of `caller` – see ceylon/ceylon-js#632.
