### ISSUE TITLE
web ide is broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-web-ide-backend#82]
Right now, the IDE is uncompilable, and even when I try to fix the error I have, I get this attempting to run code:

```
Translated code could not be parsed:
--- Error: Module name "ceylon/language/1.2.0/ceylon.language-1.2.0" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
Runtime error:
--- TypeError: Cannot read property 'Float' of undefined
Script ended with no output
```

@quintesse would you take a look please?

**Comment by quintesse** [comment]
Try clearing your browser cache, that worked for me.

**Comment by gavinking** [comment]
Well between @1e84dac69891e4d034316b2c74610dc5a9cc2999 and clearing the browser cache, I seem to have got it basically working again.

Except for module imports which aren't working and I will open a separate issue for that.
