### ISSUE TITLE
error (mangled url) importing module from Herd

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-web-ide-backend#86]
The example http://try.ceylon-lang.org/?gist=ba3fb662b75229c5739b which basically just imports:

```ceylon
    import com.vasileff.ceylon.xmath "0.0.1";
```

fails with:

> --- Error: Script error for: com/vasileff.ceylon.xmath/0.0.1/com.vasileff.ceylon.xmath-0.0.1
http://requirejs.org/docs/errors.html#scripterror

apparently due to a bad url for the module.

**Comment by quintesse** [comment]
Fixed
