### ISSUE TITLE
try.ceylon-lang.org js, css: 500 - Internal Server Error

### ISSUE THREAD

**Issue by MrMormon** [ceylon/ceylon-web-ide-backend#96]
The web ide pulls up without css or js functionality.

try.ceylon-lang.org/scripts/*
try.ceylon-lang.org/mode/*
try.ceylon-lang.org/*

all fail to load with error 500.

**Comment by quintesse** [comment]
Restarted the server. Thx for the notification!

**Comment by lucaswerkmeister** [comment]
We can close this issue, right? Seems to work now.

**Comment by MrMormon** [comment]
Oh yes, sorry.
